### PR TITLE
Fix settings update before `workspace/didChangeConfiguration` notification

### LINKED ISSUE #49: Bug: client settings do not change correctly before `workspace/didChangeConfiguration` lsp notification
After noticing that the builtin matchers worked on nvim 0.9.5 but not on nvim 0.10, I digged around a bit and it seems that according to this https://github.com/neovim/neovim/issues/27740#issuecomment-1978629315 the client settings must be set through `client.settings` reference instead of `client.config.settings` one

This will probably solve #45, #48

### PR DESCRIPTION
**Pull request by agorgl**
Fixes #49, #45, #48

### CODE REVIEW

**Review by vlada-dudr — APPROVED** [review]
It works well for me.

**Comment by umlx5h** [comment]
@someone-stole-my-name 
ping

**Comment by agorgl** [comment]
@someone-stole-my-name can we merge this?

**Comment by rgroemmer** [comment]
nice work @agorgl, im running from your branch and it works for now.
Happy to see this merged :)

**Review by someone-stole-my-name — APPROVED** [review]

**Pull request merged**
